@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package thesilverecho.avaritia.common.container;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;